apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - netbox.dev
    resources:
      - ipaddressclaims
      - ipaddresses
      - iprangeclaims
      - ipranges
      - prefixclaims
      - prefixes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - netbox.dev
    resources:
      - ipaddressclaims/finalizers
      - ipaddresses/finalizers
      - iprangeclaims/finalizers
      - ipranges/finalizers
      - prefixclaims/finalizers
      - prefixes/finalizers
    verbs:
      - update
  - apiGroups:
      - netbox.dev
    resources:
      - ipaddressclaims/status
      - ipaddresses/status
      - iprangeclaims/status
      - ipranges/status
      - prefixclaims/status
      - prefixes/status
    verbs:
      - get
      - patch
      - update
